apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
  labels:
    app: postgres
type: Opaque
data:
    postgres-root-username: cm9vdA==
    postgres-root-password: YWdwajM0MDEK
