port: 7890
socks-port: 7891
allow-lan: false
mode: Global
log-level: warning
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
proxies:
- name: 日本1
  type: ss
  server: jp1.linghun3.xyz
  port: 40010
  cipher: aes-128-gcm
  password: 4cd73d2b-b809-4c46-a6fc-710f48869f07
- name: 日本2
  type: ss
  server: jp2.linghun3.xyz
  port: 40012
  cipher: aes-128-gcm
  password: 4cd73d2b-b809-4c46-a6fc-710f48869f07
proxy-groups:
- name: ♻️ 自动选择
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - 日本1
  - 日本2
